In [1]:
import numpy as np

In [13]:
# Q1. Student Marks Analysis 

#  Ek array hai:

# marks = np.array([45, 67, 89, 32, 76, 50, 90, 29])
# Task:
# mean marks nikaalo
# std deviation nikaalo
# fail students (marks < 40) print karo
# topper ka index aur marks print karo

marks = np.array([35, 67, 89, 32, 76, 50, 90, 29, 78, 96, 78,70,30,50,78,44,69,52])
print(marks.mean())
print(np.std(marks))
print("fail",marks[marks<40])
topar_marks=marks.max()
topar_index=marks.argmax()
print("topar marks=",topar_marks)
print("topar index= ",topar_index)

61.833333333333336
21.37560915311343
fail [35 32 29 30]
topar marks= 96
topar index=  9


In [16]:
# Q2. Salary Data Cleaning
salary = np.array([25000, 30000, -5000, 40000, 5500,-10000, 50000])
# Task:
# negative salary ko 0 se replace karo
# updated array print karo
# average salary nikaalo

update=np.where(salary<0,0,salary)
print(update)
print(np.average(update))





[25000 30000     0 40000  5500     0 50000]
21500.0


In [29]:
# Q3. Temperature Analysis 🌡️
temp = np.array([30,39, 32, 35, 31, 38,40, 42, 38, 36])
# Task:
# find karo kaunse din temperature > 37
# unka index print karo
# unka average temperature nikaalo

high_temp=temp[temp>37]
print(high_temp)
index_temp=np.where(temp>37)
print(index_temp)
print(np.average(high_temp))

[39 38 40 42 38]
(array([1, 5, 6, 7, 8]),)
39.4


In [27]:
# Image Pixel Processing 
img = np.array([[120, 200, 150],
                   [30, 60, 90],
                  [255, 180, 75]])
# Task:
# brightness increase karo (+50)
# values 255 se zyada na ho (clip karo)
# final image print karo

increase_bri=np.add(img,50)
print(increase_bri)
clip_value= np.clip(increase_bri, 0,250)
print(clip_value)

[[170 250 200]
 [ 80 110 140]
 [305 230 125]]
[[170 250 200]
 [ 80 110 140]
 [250 230 125]]


In [28]:
# Q5. Prediction Threshold 
prob = np.array([0.2, 0.6,0.7,0.4,0.5, 0.8, 0.3, 0.9])
# Task:
# 0.5 threshold use karke:
# ≥0.5 → 1
# <0.5 → 0
# final prediction array banao

threshold=np.where(prob>=0.5,1,0)
print(threshold)


[0 1 1 0 1 1 0 1]
