In [1]:
import numpy as np

a=np.random.randint(1,100,24)
b=np.random.randint(1,100,24).reshape(6,4)

a

array([93, 17, 73, 35, 36, 73, 28, 59, 67, 43, 77, 64, 39,  4, 36, 34, 89,
       58, 66, 70, 83, 25, 23, 93], dtype=int32)

In [3]:
b

array([[16, 88, 69, 34],
       [25, 83, 23, 31],
       [71, 54,  5, 13],
       [21, 60,  1, 56],
       [17, 48, 99, 58],
       [53, 84, 88, 75]], dtype=int32)

In [4]:
# sort

np.sort(a)

array([10, 11, 13, 30, 30, 32, 35, 37, 42, 44, 47, 48, 57, 65, 71, 74, 75,
       76, 80, 81, 85, 88, 92, 93], dtype=int32)

In [6]:
np.sort(b)[::-1]
np.sort(b, axis=0)

array([[16, 48,  1, 13],
       [17, 54,  5, 31],
       [21, 60, 23, 34],
       [25, 83, 69, 56],
       [53, 84, 88, 58],
       [71, 88, 99, 75]], dtype=int32)

In [8]:
np.append(a,200)
np.append(b, np.random.random((b.shape[0],1)), axis=1)

array([[1.60000000e+01, 8.80000000e+01, 6.90000000e+01, 3.40000000e+01,
        8.31931452e-01],
       [2.50000000e+01, 8.30000000e+01, 2.30000000e+01, 3.10000000e+01,
        6.67895483e-01],
       [7.10000000e+01, 5.40000000e+01, 5.00000000e+00, 1.30000000e+01,
        7.86363497e-01],
       [2.10000000e+01, 6.00000000e+01, 1.00000000e+00, 5.60000000e+01,
        6.97079901e-02],
       [1.70000000e+01, 4.80000000e+01, 9.90000000e+01, 5.80000000e+01,
        5.32297568e-01],
       [5.30000000e+01, 8.40000000e+01, 8.80000000e+01, 7.50000000e+01,
        7.75819975e-01]])

In [10]:
c= np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)
np.concatenate((c,d), axis=0)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
 # unique

e= np.array([1,1,2,5,6,9,8,5,8,5,5,8,5,2,6,3,6,5,5])
np.unique(e)


array([1, 2, 3, 5, 6, 8, 9])

In [24]:
# where
a=np.array([1,5,6,8,6,8,5,2,555131,12,78,3,44,89,63,47,52,5,20,96,3,100])
np.where(a>50,0,a)
np.where(a%2==0,0,a)

array([     1,      5,      0,      0,      0,      0,      5,      0,
       555131,      0,      0,      3,      0,     89,     63,     47,
            0,      5,      0,      0,      3,      0])

In [29]:
# argmax

p=np.array([1,5,6,8,6,8,5,2,51,12,78,3,44,89,63,47,52,5,20,96,3,100])
np.argmax(p)

np.int64(21)

In [30]:
np.argmin(p)

np.int64(0)

In [32]:
p=np.array([1,5,6,8,6,8,5,2,51,12,78,3,44,89,63,47,52,5,20,96,3,97])
np.percentile(p,100)

np.float64(97.0)

In [3]:
salary=np.array([2000,4000,5000,6000,7000])
exprience=np.array([1,2,3,4,5])
np.corrcoef(salary, exprience)

array([[1.        , 0.98639392],
       [0.98639392, 1.        ]])

In [5]:
sa= np.array([10,2,5,78,96,32,45,78,56,12,82,20])
item=[5,32,82,78,52,21,20,55,79,52,20,45]
sa[np.isin(sa, item)]

array([ 5, 78, 32, 45, 78, 82, 20])

In [6]:
np.flip(sa)

array([20, 82, 12, 56, 78, 45, 32, 96, 78,  5,  2, 10])

In [8]:
item=[5,32,82,78,52,21,20,55,79,52,20,45]
np.put(item,[0,10],[100,500])

TypeError: argument 1 must be numpy.ndarray, not <class 'list'>

In [9]:
np.delete(a,[0,2,4])

array([17, 35, 73, 28, 59, 67, 43, 77, 64, 39,  4, 36, 34, 89, 58, 66, 70,
       83, 25, 23, 93], dtype=int32)